name: Run Python Tests

on: [push]  # triggers the workflow every time you push code

jobs:
  test:
    runs-on: ubuntu-latest  # uses GitHub's Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # pulls your code into the runner

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or any version you're using

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest
